### ISSUE TITLE
Why not calculate the conviction only when needed?

### ISSUE THREAD

**Issue by willjgriff** [1Hive/conviction-voting-app#19]
Perhaps I'm overlooking something, but it looks like the `calculateConviction()` function is constant so could it just be calculated all at once when it's needed eg when `executeProposal()` is called?

In this case there could be a public function for calculating the conviction for any proposal at a given time which could be used to get the most up-to-date conviction for a proposal by the Aragon app or external caller. 

If this was possible I think you could replace `blockLast` with `blockCreated` and remove the call to `calculateConviction()` in functions other than `execute()` and the setting of `blockLast`, reducing complexity and gas cost when staking and withdrawing. 

EDIT: I see you only made the `calculateConviction()` function constant in the last commit, so maybe you had this in mind anyway.

**Comment by sembrestels** [comment]
Unfortunately I think that is not possible. As you can see in the conviction formula ![y_{i+1}=x+\alpha%20y_{i}](https://latex.codecogs.com/gif.latex?y_{i+1}=x+\alpha%20y_{i}), we calculate conviction (![y](https://latex.codecogs.com/gif.latex?y)) from last conviction (![y_0](https://latex.codecogs.com/gif.latex?y_0)) and the tokens staked on a certain time  (![x](https://latex.codecogs.com/gif.latex?x)). On #16 what we do is to avoid a loop to calculate conviction for each block if the stake is constant (which saves a lot of gas), but when somebody stakes or withdraws, we have to plug the result of the last formula into the last conviction of a new one that uses the new amount of tokens staked.

This is why we save the last conviction and last block on each stake and withdraw, and if we calculate the total conviction on the last step, we would need to loop over all stakes and withdraws, being vulnerable to an out of gas attack.

But please, if you see any other possible improvement in the code tell me.

**Comment by willjgriff** [comment]
Ah I see, apologies for not looking deep enough. Otherwise it looks great man! Will keep an eye on your progress.
