### ISSUE TITLE
Contract cleanup

### ISSUE THREAD

**Issue by lkngtn** [1Hive/conviction-voting-app#2]
We ended up using the smart contract implementation of conviction voting initially deployed as part of the [gitviction](https://devpost.com/software/gitviction) hackathon project at EthParis, and focused most of our effort at the hackathon on design and frontend tasks. 

In order to get this working, we need to go back and clean-up some of the contracts particularly we need to make sure that the fund transfer mechanism is using the Vault's transfer function, and remove the code that was intended to connect to gitcoin.

**Comment by sembrestels** [comment]
Most of it has been done in the refactor. Closing in favor of #16 and #17 .
