### ISSUE TITLE
Cancelled proposals

### ISSUE THREAD

**Issue by sembrestels** [1Hive/conviction-voting-app#20]
In #10 we will create a filter for executed proposals and maybe for cancelled ones, but when do we consider a proposal to be cancelled?

- When somebody cancels it. This means to add a new `cancel(uint id)` function, a `CANCEL_PROPOSALS` permission, and give that permission to the entity that created the proposal.
- When the proposal is not new and it has no conviction on it. I would not call them closed/cancelled, because they could be reactivated at any point in time.

Thoughts on this?

**Comment by lkngtn** [comment]
I think perhaps we should take a different tact on this and start with why it is important to have a canceled state? is this to clean up the view? if things are paginated and things that are old and lack any conviction are showed last, is there a need to cancel them at all? 

Is there a technical (or UX reason) why having a canceled state is important?

**Comment by sembrestels** [comment]
If we want to order the proposals by conviction achieved, we have to calculate it for all of them. Having too many stale proposals may make this process slower, but not much slower, so I don't think it's a technical requirement to close proposals.

Regarding UX reasons, I think that many proposals can be outdated in a short period of time because they have a deadline, such as "Preparing an Aragon event during the Devcon". After the Devcon, this proposal have not any more sense, so maybe we have to conceive Conviction Voting for proposals that can be done at any time, such as the development of an app / DAO (such as conviction voting or CRDAO), or the direction a project should take (such as going for an Arachain).

I would issue the first conviction voting version without the cancelling option and see what happens. We don't have to [optimize prematurely](https://en.wikipedia.org/wiki/Program_optimization#When_to_optimize), and we can always add this feature later.

However, I would keep this issue active in order to get more feedback from the rest of the community.

**Comment by fabriziovigevani** [comment]
closed by #82
