### ISSUE TITLE
Conviction Voting section doesn't appear

### ISSUE THREAD

**Issue by vivianedias** [1Hive/conviction-voting-app#24]
I was setting up the project for the first time and the setup went well. Only when I clicked on the 'Conviction Voting' section it didn't appear. An error was logging on the console and I could figure it out what is was:

`invalid language tag: latn` in utils.js

It's strange because I'm in a country that also uses this number type, but when I changed it to 'pt-br' it worked.

**Comment by sembrestels** [comment]
Fixed in fce96f0bc22d0a1683befeda30492dbc6c3d9dcc.
