### ISSUE TITLE
Implement threshold calculation

### ISSUE THREAD

**Issue by lkngtn** [1Hive/conviction-voting-app#3]
https://github.com/1Hive/conviction-voting/blob/4da0c82e0b1ac0f02e050f152331951bc10d819f/contracts/ConvictionVotingApp.sol#L166

In the current contract instance the threshold function is not working as intended. Based on the simulation work done [here](https://github.com/BlockScience/conviction) it should be a function of the proportion of funds requested from the shared pool (vault). 

![image](https://user-images.githubusercontent.com/4986634/63855451-6edb6100-c96d-11e9-9b89-4c25c0e4f620.png)

**Comment by sembrestels** [comment]
This issue was solved on d7919c540989cded9b2e1e76fff87521f111f2a0.
