### ISSUE TITLE
Commons Template

### ISSUE THREAD

**Issue by sembrestels** [1Hive/conviction-voting-app#46]
Adjust the existing fundraising template by essentially removing the "board token manager, board token,  board voting" apps, and then replacing finance with conviction voting. If we want to get closer to ABC design we would set the tap rate to 0, and set the sell fee to a non-zero amount (_from @lkngtn message in keybase_).

**Comment by lkngtn** [comment]
Work on this is happening in https://github.com/1Hive/gardens-template
