### ISSUE TITLE
Polish frontend based on figma designs

### ISSUE THREAD

**Issue by lkngtn** [1Hive/conviction-voting-app#5]
We have created designs for the app using figma, and we should use this as the source of truth for the design implementation. While most of the components of the design have been implemented, we need to do some polishing to more closely match the intended design. 

https://www.figma.com/file/MH2ntFCnKC1O91HS8lWmDb/Conviction-Voting?node-id=1%3A2280

**Comment by sembrestels** [comment]
The new figma is this one: https://www.figma.com/file/2dwlLIN4cFbfCRjCPTsjhc/Conviction-Voting?node-id=0%3A1

**Comment by vivianedias** [comment]
maybe post here the new figma design link? @sembrestels
