### ISSUE TITLE
Add Role to Remove Proposal

### ISSUE THREAD

**Issue by lkngtn** [1Hive/conviction-voting-app#50]
There is currently no way to remove an active proposal. Besides being a waste to keep old proposals which are not popular around forever in the interface, this also means there is no way to moderate proposals after they have been created. 

Adding a function to remove an active proposal and protecting it with a role will allow for moderators to be assigned to manage proposals, or for Aragon Agreements to be used instead of moderators when it becomes available.

**Comment by sembrestels** [comment]
Sure. Closing in favor of #20.
