### ISSUE TITLE
Do not show support/withdraw buttons if account has no tokens

### ISSUE THREAD

**Issue by sembrestels** [1Hive/conviction-voting-app#55]
Buttons should be disabled if we are not in the right network, or our account has no tokens.

**Comment by GriffGreen** [comment]
or the clicking them will display an error explaining what they need to do to fix the problem... this is what we do on the giveth dapp, when they are on the wrong network we show them a little gif to help them out:

![Giveth - switch to Rinkeby on Metamask](https://user-images.githubusercontent.com/14945613/80283223-45e6b800-8716-11ea-928f-ff56f8a6c039.gif)

**Comment by sembrestels** [comment]
Yes, I agree that we should add a label to be shown when the mouse rolls over the disabled button :+1:.
