### ISSUE TITLE
Ambiguous Plots: coloring and/or labels needed

### ISSUE THREAD

**Issue by mzargham** [1Hive/conviction-voting-app#59]
as i understand it the visual is meant to show the "current projection" for conviction and the projection conditioned on my action (if i take it).
<img width="825" alt="Screenshot 2020-04-26 10 14 10" src="https://user-images.githubusercontent.com/10465438/80314587-48452280-87a7-11ea-9faf-5edd792f0fe0.png">

https://rinkeby.aragon.org/#/cv-signal-demo/0xc5bcb65d49e5f024940b5bb835d8a175501c5792/proposal/1/

style or label changes could help; can we have 2 colors? there are two concepts that need to be captured: 
- trajectory of what happens if i support or don't support
- which trajectory I am currently on (of the two above)

Also the time scale is unclear. i see the anchoring on the present but the x axis needs some sort of label so i can tell what this time frame is, blocks? hours? days?

**Comment by lkngtn** [comment]
Closing for now since we are not prioritizing the client application frontend, can re-open or reference if we pick up work on a visualization of conviction.
