### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by sembrestels** [1Hive/conviction-voting-app#7]
Consider a `vault` with 15000 DAI, and a `token` TKN with a total supply of 45000 (_root account_ has 30000 TKN and _user account_ has 15000 TKN).
 
Write a test with the following calls:
```javascript
api.addProposal('Conviction Voting', '0x', 1000, user, {from: root})
// on time 20
api.stakeToProposal(1, 1000, { from: root })
// on time 30
api.stakeToProposal(1, 1000, { from: user })
// on time 50
api.withdrawFromProposal(1, 1000, { from: root })
// on time 60
api.stakeToProposal(1, 6000, {from: user})
// on time 100
api.enactProposal(1);
```
It should pass.

Repeat the test for proposal 2:
```javascript
api.addProposal('Aragon Sidechain', '0x', 2000, root, {from: user})
```
It should not pass.

**Comment by SabaunT** [comment]
did anybody have `RangeError: Maximum call stack size exceeded` when `npx truffle test`?

**Comment by sembrestels** [comment]
I created a first test (here https://github.com/1Hive/conviction-voting-app/commit/608479861ef00dd1719a2e373597acd43a8ba30c) so it may be easier to add new ones now.

To run them it is better to use `npm test`, because it deploys a test ganache network, and takes care of everything.

**Comment by SabaunT** [comment]
Yeah, I wanted to add some tests, but I still get `RangeError: Maximum call stack size exceeded` with a  use of `npm test`.

**Comment by sembrestels** [comment]
I'm not sure, but it may be because of the node version. Which one are you using? The one that is pretty well supported by aragon-cli is `v10.17.0`.

**Comment by SabaunT** [comment]
Alright, it was because of node version, thanks a lot!
And wait for new test ;)

**Comment by SabaunT** [comment]
did I get right, that tests require time increase? or you mean something else by this?
```
// on time
```

**Comment by sembrestels** [comment]
Yes, it means to execute after a certain number of blocks. I think this [can be achieved](https://medium.com/edgefund/time-travelling-truffle-tests-f581c1964687) with the `evm_mine` function.

On the other hand, stake token, funds token and vault should also be mocked (because now the app is initialized with them set at `0x0`).

**Comment by SabaunT** [comment]
do you mean `requestedToken` by `TKN`?

**Comment by sembrestels** [comment]
> It means that for tests we should increase block number for x10 (20, 50 e.t.c) times, doesn't it?

Conviction is time dependent, so between one call and the next we need to mine the number of blocks that are stated in the comment, yes.

> do you mean requestedToken by TKN?

No, stakeToken is TKN and requestedToken is DAI for this test.

**Comment by SabaunT** [comment]
#32 review, please :)

**Comment by sembrestels** [comment]
Thank you so much for your work again, @SabaunT.
