### ISSUE TITLE
Do we need more than one token?

### ISSUE THREAD

**Issue by sembrestels** [1Hive/conviction-voting-app#8]
A conviction voting app is connected to a vault that can store many different tokens. If we give support to all of them, we need to show all token balances on the user interface, and we need to specify on every proposal what token is being requested. The threshold also will vary from token to token.

My question is, from a user experience point of view, is it useful for users to have that many tokens with different thresholds in just one interface? Which is the general use case? Proposers are going to ask for that different range of tokens or just one (probably DAI?).

We can also cover the general use case by installing the conviction voting many times, and specify on each of them the token it is going to be requested (similar to the Token Manager app).

Does it make sense, or do you prefer a single app with an integrated interface for managing all the tokens?

**Comment by lkngtn** [comment]
> My question is, from a user experience point of view, is it useful for users to have that many tokens with different thresholds in just one interface? Which is the general use case? Proposers are going to ask for that different range of tokens or just one (probably DAI?).

I know that at the hackathon we had leaned towards supporting multiple assets, but I think the general use case is probably that one token/currency will be used for proposals. And in the event that an org would support multiple assets, it probably would be a relatively small list, eg DAI and Organization Tokens. 

> We can also cover the general use case by installing the conviction voting many times, and specify on each of them the token it is going to be requested (similar to the Token Manager app).

Agreed, if we decide to just support one token (set at initialization), it would be reasonable to install multiple instances of the app. 

> Does it make sense, or do you prefer a single app with an integrated interface for managing all the tokens? 

I'm comfortable with simplifying things (both technically and from a UX perspective) by choosing to only support a single asset for each instance of conviction voting. 👍
